### ISSUE TITLE
griffe cannot find valid inline injection links

### ISSUE THREAD

**Issue by nerdoc** [mkdocstrings/griffe#121]
**Describe the bug**
griffe crashes when parsing django code.
I can't get further with my MkDocs page, as `mkdocs server` always spills out some information I don't know what to do with:

**To Reproduce**
Steps to reproduce the behavior (given you have a working virtualenv):

```bash
git clone https://gitlab.com/nerdocs/medux/medux/-/commit/8b0603e63c44c49ec268abee188ce10a65e63b45 --depth 1
cd medux
virtualenv .venv
. .venv/bin/activate
pip install flit
flit install --only-deps
mkdocs serve
```
This should go well. Now, open `docs/middleware.md` and uncomment the line `::: medux.core.middleware`. (or any other .md file, and write a valid ::: directive into it)

There you get the error:
```
ERROR    -  Error reading page 'middleware.md': Could not resolve django.conf.settings
Traceback (most recent call last):
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/griffe/dataclasses.py", line 960, in resolve_target
    resolved = self.modules_collection[self.target_path]
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/griffe/mixins.py", line 28, in __getitem__
    return self.members[parts[0]][parts[1:]]  # type: ignore[attr-defined]
KeyError: 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/christian/Projekte/medux/.venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/mkdocs/__main__.py", line 234, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 116, in serve
    server.serve()
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/mkdocs/livereload/__init__.py", line 162, in serve
    self._build_loop()
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/mkdocs/livereload/__init__.py", line 184, in _build_loop
    func()
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 76, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/mkdocs/commands/build.py", line 308, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/mkdocs/commands/build.py", line 181, in _populate_page
    page.render(config, files)
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/mkdocs/structure/pages.py", line 270, in render
    self.content = md.convert(self.markdown)
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/markdown/core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/mkdocstrings/extension.py", line 121, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/mkdocstrings/extension.py", line 195, in _process_block
    data: CollectorItem = handler.collect(identifier, options)
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/mkdocstrings_handlers/python/handler.py", line 217, in collect
    unresolved, iterations = loader.resolve_aliases(implicit=False, external=False)
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/griffe/loader.py", line 217, in resolve_aliases
    next_resolved, next_unresolved = self.resolve_module_aliases(module, implicit, external)
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/griffe/loader.py", line 357, in resolve_module_aliases
    sub_resolved, sub_unresolved = self.resolve_module_aliases(
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/griffe/loader.py", line 357, in resolve_module_aliases
    sub_resolved, sub_unresolved = self.resolve_module_aliases(
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/griffe/loader.py", line 335, in resolve_module_aliases
    if not implicit and not member.is_explicitely_exported:
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/griffe/dataclasses.py", line 827, in __getattr__
    attr = getattr(self.target, name)
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/griffe/dataclasses.py", line 936, in target
    self.resolve_target()
  File "/home/christian/Projekte/medux/.venv/lib/python3.10/site-packages/griffe/dataclasses.py", line 962, in resolve_target
    raise AliasResolutionError(self.target_path) from error
griffe.exceptions.AliasResolutionError: Could not resolve django.conf.settings

Process finished with exit code 1
```

**Expected behavior**
I would expect that mkdocs compiles the code normally

**System (please complete the following information):**
- `griffe` version: 0.24.1
- Python version: 3.10
- OS: Linux

**Additional context**
as this looks similar to #39, I think it's a griffe issue and not a mkdocstrings issue. Sorry If I got that wrong.

**Comment by pawamoy** [comment]
Hi, thanks for the report. Could you try against master? I've several things but did not released them yet.
`pip install git+https://github.com/mkdocstrings/griffe`

**Comment by nerdoc** [comment]
Thanks, that (whatever) definitely fixes the issue!

**Comment by pawamoy** [comment]
Great! I'll try to publish a new release soon :)
