### ISSUE TITLE
Include the location of the mistake in case of a "Could not resolve X" error

### ISSUE THREAD

**Issue by Aran-Fey** [mkdocstrings/griffe#130]
**Is your feature request related to a problem? Please describe.**
I'm trying to generate documentation for my project with `mkdocstrings`, and griffe constantly crashes with weird "Could not resolve X" errors that are impossible to track down and fix.

**Describe the solution you'd like**
The error message should include the exact location of the symbol that couldn't be resolved.

**Additional context**
This is the error I get running `mkdocs serve` on my project:

```
ERROR    -  Error reading page 'api_reference.md': Could not resolve typing._no_init_or_replace_init
Traceback (most recent call last):
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\griffe\dataclasses.py", line 1111, in _resolve_target
    resolved = self.modules_collection[self.target_path]
               ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\griffe\mixins.py", line 28, in __getitem__
    return self.members[parts[0]][parts[1:]]  # type: ignore[attr-defined]
           ~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'typing'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\mkdocs\__main__.py", line 301, in <module>
    cli()
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\mkdocs\__main__.py", line 234, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\mkdocs\commands\serve.py", line 83, in serve
    builder(config)
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\mkdocs\commands\serve.py", line 76, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\mkdocs\commands\build.py", line 308, in build
    _populate_page(file.page, config, files, dirty)
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\mkdocs\commands\build.py", line 181, in _populate_page
    page.render(config, files)
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\mkdocs\structure\pages.py", line 270, in render
    self.content = md.convert(self.markdown)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\markdown\core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\markdown\blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\markdown\blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\markdown\blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\mkdocstrings\extension.py", line 116, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\mkdocstrings\extension.py", line 202, in _process_block
    rendered = handler.render(data, options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\mkdocstrings_handlers\python\handler.py", line 255, in render
    return template.render(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\mkdocstrings_handlers\python\templates\material\module.html", line 1, in top-level template code
    {% extends "_base/module.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\mkdocstrings_handlers\python\templates\material\_base\module.html", line 58, in top-level template code
    {% include "children.html" with context %}
^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\mkdocstrings_handlers\python\templates\material\children.html", line 1, in top-level template code
    {% extends "_base/children.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\mkdocstrings_handlers\python\templates\material\_base\children.html", line 45, in top-level template code
    {% include "class.html" with context %}
^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\mkdocstrings_handlers\python\templates\material\class.html", line 1, in top-level template code
    {% extends "_base/class.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\mkdocstrings_handlers\python\templates\material\_base\class.html", line 30, in top-level template code
    {%- include "signature.html" with context -%}
^^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\mkdocstrings_handlers\python\templates\material\signature.html", line 1, in top-level template code
    {% extends "_base/signature.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\mkdocstrings_handlers\python\templates\material\_base\signature.html", line 12, in top-level template code
    {%- for parameter in function.parameters -%}
^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\griffe\dataclasses.py", line 1035, in parameters
    return cast(Function, self.target).parameters
                          ^^^^^^^^^^^
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\griffe\dataclasses.py", line 1078, in target
    self.resolve_target()
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\griffe\dataclasses.py", line 1105, in resolve_target
    self._resolve_target()
  File "C:\Users\Aran-Fey\AppData\Roaming\Python\Python311\site-packages\griffe\dataclasses.py", line 1113, in _resolve_target
    raise AliasResolutionError(self.target_path) from error
griffe.exceptions.AliasResolutionError: Could not resolve typing._no_init_or_replace_init
```

My project doesn't contain `typing._no_init_or_replace_init` anywhere. I have no idea what's causing this error or how to fix it. I would like to see a more helpful error message, something along the lines of

> Could not resolve "typing._no_init_or_replace_init" in class "Foo" from "my_project/foo.py"

**Comment by pawamoy** [comment]
Hello, thanks for the report! And this is a good suggestion. Do you have a public repository I could use to replicate and fix this particular issue?

**Comment by Aran-Fey** [comment]
Unfortunately this particular crash is pretty tricky to reproduce. I still haven't quite figured it out yet, but this one in particular is probably my own fault (I'm doing something unusual with my `PYTHONPATH` and other things). I'll probably open another issue related to that, because there's something weird about how griffe discovers modules, and it's making it very difficult for me to debug this.

**Comment by Aran-Fey** [comment]
Ok, I give up. I'm sorry, but I can't for the life of me isolate this bug. I have a demo, which you can download [here](https://app.box.com/s/nzpmao8b5adh9jfh7ie6opkq4i6qwj9o), but it's far from minimal - I've had to include no less than 4 of my projects. (Instructions for reproducing the issue are included in the zip file.)

I've discovered that the issue is indeed related to my crazy setup - I have an `__init__.py` file in the project directory. Deleting that file makes the error go away, but in exchange the generated API documentation is completely blank. So I figured it's still worth reporting. Something very weird is going on there.

**Comment by pawamoy** [comment]
Thanks, I'll have a look at it.

**Comment by pawamoy** [comment]
Yep, I confirm the behavior you describe. I'm able to replicate the issue in my shell, but not in VSCode, so I can't debug :rofl:

**Comment by pawamoy** [comment]
About the docs being blank: you need to enable showing submodules:

```
::: animation_editor
    options:
        show_submodules: true
```

**Comment by Aran-Fey** [comment]
Oh, huh. Ok, rookie mistake on my part. But I swear I *have* seen documentation being generated today even without that setting enabled. Nothing makes sense to me anymore...

**Comment by pawamoy** [comment]
It's more clear after a break usually :wink:

I've pushed a commit that should improve the messages of alias resolution errors. You can try it by installing from master branch. Otherwise I'll publish a new release soon.

**Comment by Aran-Fey** [comment]
What about the `griffe.exceptions.AliasResolutionError: Could not resolve typing._no_init_or_replace_init` error caused by the presence of an `__init__.py` file in the project root directory? Should I open a separate issue for that, or is that already taken care of?

**Comment by pawamoy** [comment]
Reading the traceback, it seems that the `__init__` method in some class of yours is actually an alias to `typing._no_init_or_replace_init`. This is the first time I encounter such a scenario. Maybe we could add a condition in the template to skip the `__init__` method if it's an alias to `typing._no_init_or_replace_init` (or just an alias).

**Comment by Aran-Fey** [comment]
The weird thing is that the presence of `typing._no_init_or_replace_init` alone doesn't make it crash. For some reason, renaming or deleting the project-level `__init__.py` file makes the crash go away. I've observed this behavior in multiple projects of mine, but I can't reproduce it in a minimal demo project...

**Comment by pawamoy** [comment]
Did you try to isolate the issue by starting from your complete setup and removing small parts one by one? (trying to help the best I can :sweat_smile: )

**Comment by pawamoy** [comment]
Hi @Aran-Fey, do you still have this issue with latest Griffe version?

**Comment by Aran-Fey** [comment]
I honestly can't say. It's been so long, I can't even reproduce the error anymore.

But anyway, feel free to close this issue. The thing I originally made the bug report/feature request for has been taken care of, after all.

I'll probably run into problems with mkdocs/mkdocstrings/griffe again in the future, but I'll just open a new issue then.

**Comment by pawamoy** [comment]
Alright, thanks!
