### ISSUE TITLE
Allow ignoring single files or properties

### ISSUE THREAD

**Issue by LukeSavefrogs** [mkdocstrings/griffe#131]
# Description
I find myself in a situation where I have multiple "temporary" variables, which i don't want to be included in the documentation.
Some examples:
- In the `__init__.py` file
  ```python
  __all__ = ["members"]
  ```
- In a submodule (neither of them should show up):
  ```python
  T = TypeVar('T', str)
  type_alias: TypeAlias = T
  ```
- In a utility/test script:
  ```python
  def main():
     ...
  ```

# Disclaimer
- **I already know about the `filters` configuration option**, but in big projects with similar or even equal names in different files it's difficult to differentiate between one and another.
In addition, this proposals advances the concept of file filtering, which AFAIK is not supported by the `filters` option.
- I also know **i could set `show_if_no_docstring: false`** to hide temporary members with no docstrings but:
  1. Sometimes I have functions which **have docstrings** but need to **remain private**, such as utility or internal methods.
  2. I **have to leave `show_if_no_docstring: true`** since at the moment i cannot document every single property i want to be shown (thousands of module methods to be documented is not an easy work 🤕).

This makes clear that it would be simpler for some users to just specify which file or member (_function, variable, class, etc..._) to exclude from the documentation.

# Proposals
As said by others, it would be greatly useful to include a "magic string" to disable the parsing of the current scope.
It could be inside the docstring or the comment preceding (only if contains that word, does not have any effect on the actual docstring).

I used `@griffe-ignore` as a sort of placeholder, since i come from the Typescript world and i liked this name 😃 

## Proposal 1
In this proposal the `@griffe-ignore` is placed as a comment before the member that should be ignored.

**Pros**:
- **Cleaner documentation**: Is not included by IDEs in the autocompletion dialog, leaving more space to the actual member documentation.
- In line with existing statements like `# type: ignore`

**Cons**:
- I suppose it's **not easy to implement** 

### Examples
- At the start of the `src/mypackage/util-file.py` utility file which i want to exclude:
   - As a comment:
      ```python
      # @griffe-ignore
      # Actual code goes after...
      ```
- Variable (`@griffe-ignore` must be the only word present in its line):
  ```python
  # @griffe-ignore
  temp_variable = "test"
  """ An internal variable i don't wanto to show """
  ```
- Class (`@griffe-ignore` must be the only word present in its line):
  ```python
  # @griffe-ignore
  class TEST(object):
      """ My test class """
  ...
  ```

It would be even better then if one could also write the comment at the right of the variable:
```python
temp_variable = "test" # @griffe-ignore
```
And this syntax would be equivalent to writing:
```python
# @griffe-ignore
temp_variable = "test"
```

## Proposal 2
In this proposal the `@griffe-ignore` is inside the docstring.

**Pros**:
- Easier to implement

**Cons**:
- Can get messy and interfere with the IDE suggestion (it would show up in the suggestion dialog, which could be unwanted to final users).

### Examples
- At the start of the `src/mypackage/util-file.py` utility file which i want to exclude:
  ```python
  """ @griffe-ignore """
  # Actual code goes after...
  ```
- Variable (`@griffe-ignore` must be the only word present in its line):
  ```python
  temp_variable = "test"
  """ An internal variable i don't wanto to show
  @griffe-ignore
  """
  ```
- Class (`@griffe-ignore` must be the only word present in its line):
  ```python
  class TEST(object):
      """ My test class
      @griffe-ignore
      """
  ...
  ```
# Related issues
This is related to the following issues:
- [pytkdocs #40](https://github.com/mkdocstrings/pytkdocs/issues/40)
- [griffe #67](https://github.com/mkdocstrings/griffe/issues/67)

**Comment by LukeSavefrogs** [comment]
The workaround you suggested seems really interesting!

However it doesn't work for me. The extension isn't even loaded 😢 

I tried the following:
- `griffe_prune`:
  ```
  INFO     -  Building documentation...
  INFO     -  Cleaning site directory
  ERROR    -  Error reading page 'reference/wsadmin_type_hints/index.md': Extension module
              'griffe_prune' could not be found
  Traceback (most recent call last):
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\griffe\agents\extensions\base.py", line 258, in load_extension
      ext_module = dynamic_import(import_path)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\griffe\importer.py", line 59, in dynamic_import
      module = import_module(module_path)
    File "C:\Python39\lib\importlib\__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
  ModuleNotFoundError: No module named 'griffe_prune'
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Python39\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\click\core.py", line 1130, in __call__
      return self.main(*args, **kwargs)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\click\core.py", line 1055, in main
      rv = self.invoke(ctx)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\click\core.py", line 1657, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\click\core.py", line 1404, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\click\core.py", line 760, in invoke
      return __callback(*args, **kwargs)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocs\__main__.py", line 234, in serve_command
      serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocs\commands\serve.py", line 83, in serve
      builder(config)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocs\commands\serve.py", line 76, in builder
      build(config, live_server=live_server, dirty=dirty)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocs\commands\build.py", line 308, in build
      _populate_page(file.page, config, files, dirty)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocs\commands\build.py", line 181, in _populate_page
      page.render(config, files)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocs\structure\pages.py", line 270, in render
      self.content = md.convert(self.markdown)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\markdown\core.py", line 264, in convert
      root = self.parser.parseDocument(self.lines).getroot()
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\markdown\blockparser.py", line 90, in parseDocument
      self.parseChunk(self.root, '\n'.join(lines))
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\markdown\blockparser.py", line 105, in parseChunk
      self.parseBlocks(parent, text.split('\n\n'))
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\markdown\blockparser.py", line 123, in parseBlocks
      if processor.run(parent, blocks) is not False:
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocstrings\extension.py", line 116, in run
      html, handler, data = self._process_block(identifier, block, heading_level)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocstrings\extension.py", line 188, in _process_block
      data: CollectorItem = handler.collect(identifier, options)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocstrings_handlers\python\handler.py", line 205, in collect
      extensions=load_extensions(final_config.get("extensions", [])),
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\griffe\agents\extensions\base.py", line 281, in load_extensions
      extensions.add(load_extension(extension))
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\griffe\agents\extensions\base.py", line 260, in load_extension
      raise ExtensionNotLoadedError(f"Extension module '{import_path}' could not be found") from error 
  griffe.exceptions.ExtensionNotLoadedError: Extension module 'griffe_prune' could not be found        
  ```
- `./griffe_prune`: 
  ```
  INFO     -  Building documentation...
  INFO     -  Cleaning site directory
  ERROR    -  Error reading page 'reference/wsadmin_type_hints/index.md': the 'package' argument is
              required to perform a relative import for './griffe_prune'
  Traceback (most recent call last):
    File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Python39\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\click\core.py", line 1130, in __call__
      return self.main(*args, **kwargs)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\click\core.py", line 1055, in main
      rv = self.invoke(ctx)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\click\core.py", line 1657, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\click\core.py", line 1404, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\click\core.py", line 760, in invoke
      return __callback(*args, **kwargs)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocs\__main__.py", line 234, in serve_command
      serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocs\commands\serve.py", line 83, in serve
      builder(config)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocs\commands\serve.py", line 76, in builder
      build(config, live_server=live_server, dirty=dirty)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocs\commands\build.py", line 308, in build
      _populate_page(file.page, config, files, dirty)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocs\commands\build.py", line 181, in _populate_page
      page.render(config, files)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocs\structure\pages.py", line 270, in render
      self.content = md.convert(self.markdown)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\markdown\core.py", line 264, in convert
      root = self.parser.parseDocument(self.lines).getroot()
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\markdown\blockparser.py", line 90, in parseDocument
      self.parseChunk(self.root, '\n'.join(lines))
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\markdown\blockparser.py", line 105, in parseChunk
      self.parseBlocks(parent, text.split('\n\n'))
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\markdown\blockparser.py", line 123, in parseBlocks
      if processor.run(parent, blocks) is not False:
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocstrings\extension.py", line 116, in run
      html, handler, data = self._process_block(identifier, block, heading_level)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocstrings\extension.py", line 188, in _process_block
      data: CollectorItem = handler.collect(identifier, options)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocstrings_handlers\python\handler.py", line 205, in collect
      extensions=load_extensions(final_config.get("extensions", [])),
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\griffe\agents\extensions\base.py", line 283, in load_extensions
      extensions.add(load_extension(extension))
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\griffe\agents\extensions\base.py", line 260, in load_extension
      ext_module = dynamic_import(import_path)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\griffe\importer.py", line 59, in dynamic_import
      module = import_module(module_path)
    File "C:\Python39\lib\importlib\__init__.py", line 122, in import_module
      raise TypeError(msg.format(name))
  TypeError: the 'package' argument is required to perform a relative import for './griffe_prune'      
  ```
- `.griffe_prune`:
  ```
  INFO     -  Building documentation...
  INFO     -  Cleaning site directory
  ERROR    -  Error reading page 'reference/wsadmin_type_hints/index.md': the 'package' argument is
              required to perform a relative import for '.griffe_prune'
  Traceback (most recent call last):
    File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Python39\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\click\core.py", line 1130, in __call__
      return self.main(*args, **kwargs)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\click\core.py", line 1055, in main
      rv = self.invoke(ctx)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\click\core.py", line 1657, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\click\core.py", line 1404, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\click\core.py", line 760, in invoke
      return __callback(*args, **kwargs)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocs\__main__.py", line 234, in serve_command
      serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocs\commands\serve.py", line 83, in serve
      builder(config)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocs\commands\serve.py", line 76, in builder
      build(config, live_server=live_server, dirty=dirty)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocs\commands\build.py", line 308, in build
      _populate_page(file.page, config, files, dirty)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocs\commands\build.py", line 181, in _populate_page
      page.render(config, files)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocs\structure\pages.py", line 270, in render
      self.content = md.convert(self.markdown)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\markdown\core.py", line 264, in convert
      root = self.parser.parseDocument(self.lines).getroot()
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\markdown\blockparser.py", line 90, in parseDocument
      self.parseChunk(self.root, '\n'.join(lines))
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\markdown\blockparser.py", line 105, in parseChunk
      self.parseBlocks(parent, text.split('\n\n'))
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\markdown\blockparser.py", line 123, in parseBlocks
      if processor.run(parent, blocks) is not False:
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocstrings\extension.py", line 116, in run
      html, handler, data = self._process_block(identifier, block, heading_level)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocstrings\extension.py", line 188, in _process_block
      data: CollectorItem = handler.collect(identifier, options)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\mkdocstrings_handlers\python\handler.py", line 205, in collect
      extensions=load_extensions(final_config.get("extensions", [])),
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\griffe\agents\extensions\base.py", line 281, in load_extensions
      extensions.add(load_extension(extension))
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\griffe\agents\extensions\base.py", line 258, in load_extension
      ext_module = dynamic_import(import_path)
    File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\wsadmin-type-hints-YFufmD5a-py3.9\lib\site-packages\griffe\importer.py", line 59, in dynamic_import
      module = import_module(module_path)
    File "C:\Python39\lib\importlib\__init__.py", line 122, in import_module
      raise TypeError(msg.format(name))
  TypeError: the 'package' argument is required to perform a relative import for '.griffe_prune'       
  ```

**Comment by pawamoy** [comment]
The `griffe_prune.py` must be importable. If it's in the current directory when you run MkDocs, try this: `PYTHONPATH=. mkdocs serve`.

**Comment by LukeSavefrogs** [comment]
> The `griffe_prune.py` module must be importable. If it's in the current directory when you run MkDocs, try this: `PYTHONPATH=. mkdocs serve`.

Ok, i did as you told and now this is the error I'm facing:
```
  File "C:\Users\lucas\Desktop\Unicredit\wsadmin-objects\docs\scripts\griffe_prune.py", line 15, in visit
    if self.visitor.current.members[node.name].path in prune:
AttributeError: 'Constant' object has no attribute 'name'
```

**Comment by pawamoy** [comment]
Ah, better! Just the code I suggested that is failing, and indeed I did not test it. It's probably a bit too brutal to override the visit method directly. I'll try to refine it a bit later.

**Comment by pawamoy** [comment]
We have a new extension system. The above example could be rewritten as:

```python
# griffe_prune.py
from griffe.extensions import Extension

prune = {
    "some_module.some_attr",
    "some_module.SomeClass",
}


class PruneExtension(Extension):
    def on_module_members(self, node, mod):
        delete = set(member.path for member in mod.members.values()) | prune
        for path in delete:
            del mod.members[path]
```

Again, not tested :smile: But it should be more robust than the previous one.

**Comment by pawamoy** [comment]
I'm going to close this: such fine-grain filtering should be implemented downstream, typically in mkdocstrings-python. Plus we've provided workarounds with extension to "prune" Griffe object trees :slightly_smiling_face:
