### ISSUE TITLE
Legacy python handler works but new one fails when documenting a package using `argparse`

### ISSUE THREAD

**Issue by HarrisonWilde** [mkdocstrings/griffe#139]
**Describe the bug**

So I am following this tutorial https://mkdocstrings.github.io/recipes/ to automatically create a code reference for my package given its docstrings. I use the `argparse` module and when I go to `mkdocs serve` or `build` my documentation, I get the following error. This works fine if I user the `python-legacy` handler, but I would be keen to move to the new one if this can be fixed.

```
❯ mkdocs serve
INFO     -  Building documentation...
INFO     -  Cleaning site directory
ERROR    -  Error building page 'reference/cli/module_setup.md': Could not resolve argparse
Traceback (most recent call last):
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/mkdocs_autorefs/plugin.py", line 78, in _get_item_url
    return self._url_map[identifier]
KeyError: 'nhssynth.cli.module_arguments.argparse._SubParsersAction'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/griffe/dataclasses.py", line 1111, in _resolve_target
    resolved = self.modules_collection[self.target_path]
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/griffe/mixins.py", line 27, in __getitem__
    return self.members[parts[0]]  # type: ignore[attr-defined]
KeyError: 'argparse'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/harrisonwilde/.venv/nhssynth/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/mkdocs/__main__.py", line 234, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 83, in serve
    builder(config)
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 76, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/mkdocs/commands/build.py", line 329, in build
    _build_page(file.page, config, doc_files, nav, env, dirty)
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/mkdocs/commands/build.py", line 234, in _build_page
    output = config.plugins.run_event('post_page', output, page=page, config=config)
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/mkdocs/plugins.py", line 520, in run_event
    result = method(item, **kwargs)
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/mkdocs_autorefs/plugin.py", line 205, in on_post_page
    fixed_output, unmapped = fix_refs(output, url_mapper)
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/mkdocs_autorefs/references.py", line 191, in fix_refs
    html = AUTO_REF_RE.sub(fix_ref(url_mapper, unmapped), html)
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/mkdocs_autorefs/references.py", line 157, in inner
    url = url_mapper(unescape(identifier))
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/mkdocs_autorefs/plugin.py", line 107, in get_item_url
    url = self._get_item_url(identifier, fallback)
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/mkdocs_autorefs/plugin.py", line 83, in _get_item_url
    new_identifiers = fallback(identifier)
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/mkdocstrings/handlers/base.py", line 531, in get_anchors
    anchors = handler.get_anchors(handler.collect(identifier, fallback_config))
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/mkdocstrings_handlers/python/handler.py", line 223, in collect
    doc_object = self._modules_collection[identifier]
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/griffe/mixins.py", line 28, in __getitem__
    return self.members[parts[0]][parts[1:]]  # type: ignore[attr-defined]
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/griffe/mixins.py", line 28, in __getitem__
    return self.members[parts[0]][parts[1:]]  # type: ignore[attr-defined]
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/griffe/mixins.py", line 28, in __getitem__
    return self.members[parts[0]][parts[1:]]  # type: ignore[attr-defined]
  [Previous line repeated 1 more time]
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/griffe/dataclasses.py", line 817, in __getitem__
    return self.target[key]
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/griffe/dataclasses.py", line 1078, in target
    self.resolve_target()
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/griffe/dataclasses.py", line 1105, in resolve_target
    self._resolve_target()
  File "/Users/harrisonwilde/.venv/nhssynth/lib/python3.10/site-packages/griffe/dataclasses.py", line 1113, in _resolve_target
    raise AliasResolutionError(self.target_path) from error
griffe.exceptions.AliasResolutionError: Could not resolve argparse
```

**To Reproduce**
1. Follow the steps in https://mkdocstrings.github.io/recipes/ to create `gen_ref_pages.py`
```python
from pathlib import Path

import mkdocs_gen_files

nav = mkdocs_gen_files.Nav()

for path in sorted(Path("src").rglob("*.py")):
    module_path = path.relative_to("src").with_suffix("")
    doc_path = path.relative_to("src").with_suffix(".md")
    full_doc_path = Path("reference", doc_path)

    parts = tuple(module_path.parts)

    if parts[-1] == "__init__":
        parts = parts[:-1]
        doc_path = doc_path.with_name("index.md")
        full_doc_path = full_doc_path.with_name("index.md")
    elif parts[-1] == "__main__":
        continue

    nav[parts] = doc_path.as_posix()

    with mkdocs_gen_files.open(full_doc_path, "w") as fd:
        ident = ".".join(parts)
        fd.write(f"::: {ident}")

    mkdocs_gen_files.set_edit_path(full_doc_path, path)

with mkdocs_gen_files.open("reference/SUMMARY.md", "w") as nav_file:
    nav_file.writelines(nav.build_literate_nav())
```
2. Try building docs via this with a package that imports `argparse`
3. See error

**Expected behavior**

It should build without issue.

**System (please complete the following information):**
- `griffe` version: 0.25.5
- Python version: 3.10.10
- OS: macOS

**Comment by pawamoy** [comment]
This should be fixed by https://github.com/mkdocstrings/python/commit/a190e2c4a752e74a05ad03702837a0914c198742, will release soon.
