### ISSUE TITLE
KeyError: 'python3'

### ISSUE THREAD

**Issue by vinRosso** [mkdocstrings/griffe#157]
**Describe the bug**
Serving the documentation raises this error

```
ERROR    -  Error reading page 'reference.md': 'python3'
Traceback (most recent call last):
  File "/maya_venv/lib/python3.7/site-packages/griffe/loader.py", line 540, in _get_or_create_parent_module
    parent_module = parent_module[parent_part]
  File "/maya_venv/lib/python3.7/site-packages/griffe/mixins.py", line 31, in __getitem__
    return self.members[parts[0]][parts[1:]]  # type: ignore[attr-defined]
KeyError: 'python3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/maya_venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/maya_venv/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/maya_venv/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/maya_venv/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/maya_venv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/maya_venv/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/maya_venv/lib/python3.7/site-packages/mkdocs/__main__.py", line 234, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/maya_venv/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 83, in serve
    builder(config)
  File "/maya_venv/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 76, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/maya_venv/lib/python3.7/site-packages/mkdocs/commands/build.py", line 308, in build
    _populate_page(file.page, config, files, dirty)
  File "/maya_venv/lib/python3.7/site-packages/mkdocs/commands/build.py", line 181, in _populate_page
    page.render(config, files)
  File "/maya_venv/lib/python3.7/site-packages/mkdocs/structure/pages.py", line 270, in render
    self.content = md.convert(self.markdown)
  File "/maya_venv/lib/python3.7/site-packages/markdown/core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/maya_venv/lib/python3.7/site-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/maya_venv/lib/python3.7/site-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/maya_venv/lib/python3.7/site-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/maya_venv/lib/python3.7/site-packages/mkdocstrings/extension.py", line 127, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
  File "/maya_venv/lib/python3.7/site-packages/mkdocstrings/extension.py", line 199, in _process_block
    data: CollectorItem = handler.collect(identifier, options)
  File "/maya_venv/lib/python3.7/site-packages/mkdocstrings_handlers/python/handler.py", line 269, in collect
    loader.load_module(module_name)
  File "/maya_venv/lib/python3.7/site-packages/griffe/loader.py", line 127, in load_module
    top_module = self._load_package(package, submodules=submodules)
  File "/maya_venv/lib/python3.7/site-packages/griffe/loader.py", line 399, in _load_package
    top_module = self._load_module(package.name, package.path, submodules=submodules)
  File "/maya_venv/lib/python3.7/site-packages/griffe/loader.py", line 418, in _load_module
    return self._load_module_path(module_name, module_path, submodules=submodules, parent=parent)
  File "/maya_venv/lib/python3.7/site-packages/griffe/loader.py", line 447, in _load_module_path
    self._load_submodules(module)
  File "/maya_venv/lib/python3.7/site-packages/griffe/loader.py", line 452, in _load_submodules
    self._load_submodule(module, subparts, subpath)
  File "/maya_venv/lib/python3.7/site-packages/griffe/loader.py", line 456, in _load_submodule
    parent_module = self._get_or_create_parent_module(module, subparts, subpath)
  File "/maya_venv/lib/python3.7/site-packages/griffe/loader.py", line 544, in _get_or_create_parent_module
    parent_module[parent_part] = next_parent_module
  File "/maya_venv/lib/python3.7/site-packages/griffe/mixins.py", line 91, in __setitem__
    self.members[parts[0]][parts[1:]] = value  # type: ignore[attr-defined]
KeyError: 'python3'
```

**System:**
- `griffe` version: 0.27.5
- Python version: 3.7
- OS: Linux CentOs 7

**Additional context**
I'm building an Autodesk Maya tool documentation

**Comment by pawamoy** [comment]
Hey, thanks for the report. Do you have a public repository I could use to investigate? The traceback is not enough here.

**Comment by vinRosso** [comment]
Unluckily it's a private repository since it's work related stuff that I can't share.
What could I do to debug this error or to help you finding the issue?

**Comment by pawamoy** [comment]
You could try to find a minimum reproducible example of the issue. Copy your whole project to a new folder, and try to identify the problematic modules by removing them one after the other.

You should particularly look at any object or module in your code base containing `python3` in its name (do you have any?).

**Comment by vinRosso** [comment]
Thanks, I found the issue.
We were dragging behind some old venv inside the project, which contained links to the python executables.
Removing the environment fixed the bug.

![image](https://github.com/mkdocstrings/griffe/assets/22852084/e4118bb1-c3f7-4963-b7ac-a20b40483b62)

**Comment by pawamoy** [comment]
OK, thanks for reporting back! Closing then :slightly_smiling_face:
