### ISSUE TITLE
griffe fails to unparse `ast.Call ` at `ast.NamedExpr` (containing an assignment expression)

### ISSUE THREAD

**Issue by lagru** [mkdocstrings/griffe#166]
**Describe the bug**

I tried running griffe on scikit-image's current `main` branch (e.g. see commit https://github.com/scikit-image/scikit-image/blob/821c9f249df5c3cd0a5e885db8fbf3f659b65ef0) which seems to fail on this part https://github.com/scikit-image/scikit-image/blob/821c9f249df5c3cd0a5e885db8fbf3f659b65ef0/skimage/transform/tests/test_geometric.py#L584-L601 with 

```
ERROR      Failed to unparse node <ast.Call object at 0x7f4b30483070> at skimage/transform/tests/test_geometric.py:584: <class 'ast.NamedExpr'>
...
AttributeError: 'NoneType' object has no attribute 'split'
```

Below I've included a minimal example that reproduces the same error as included in the debug log below.

**Debug logs**

<details>
<summary>Debug log, click to expand</summary>

```console
$ griffe dump -LDEBUG -s . minimal_example
INFO       Loading package minimal_example
DEBUG      Found minimal_example: loading
DEBUG      Loading path minimal_example.py
ERROR      Failed to unparse node <ast.Call object at 0x7f14ac8b7850> at minimal_example.py:12: <class 'ast.NamedExpr'>
Traceback (most recent call last):
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/nodes.py", line 1240, in safe_get_value
return get_value(node)
^^^^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/nodes.py", line 1226, in get_value
return _node_value_map[type(node)](node)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/nodes.py", line 875, in _get_call_value
posargs = ", ".join(_get_value(arg) for arg in node.args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/nodes.py", line 875, in <genexpr>
posargs = ", ".join(_get_value(arg) for arg in node.args)
^^^^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/nodes.py", line 1212, in _get_value
return _node_value_map[type(node)](node)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/nodes.py", line 871, in _get_boolop_value
return _get_value(node.op).join(_get_value(value) for value in node.values)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/nodes.py", line 871, in <genexpr>
return _get_value(node.op).join(_get_value(value) for value in node.values)
^^^^^^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/nodes.py", line 1212, in _get_value
return _node_value_map[type(node)](node)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/nodes.py", line 885, in _get_call_value
return f"{_get_value(node.func)}({args})"
^^^^^^^^^^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/nodes.py", line 1212, in _get_value
return _node_value_map[type(node)](node)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/nodes.py", line 851, in _get_attribute_value
return f"{_get_value(node.value)}.{node.attr}"
^^^^^^^^^^^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/nodes.py", line 1212, in _get_value
return _node_value_map[type(node)](node)
~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: <class 'ast.NamedExpr'>
Traceback (most recent call last):
File "~/.local/lib/venv/skimagedev/bin/griffe", line 8, in <module>
sys.exit(main())
^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/cli.py", line 528, in main
return commands[subcommand](**opts_dict)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/cli.py", line 393, in dump
loader = _load_packages(
^^^^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/cli.py", line 166, in _load_packages
loader.load_module(package)
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/loader.py", line 127, in load_module
top_module = self._load_package(package, submodules=submodules)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/loader.py", line 399, in _load_package
top_module = self._load_module(package.name, package.path, submodules=submodules)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/loader.py", line 418, in _load_module
return self._load_module_path(module_name, module_path, submodules=submodules, parent=parent)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/loader.py", line 441, in _load_module_path
module = self._visit_module(code, module_name, module_path, parent)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/loader.py", line 487, in _visit_module
module = visit(
^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/visitor.py", line 109, in visit
).get_module()
^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/visitor.py", line 179, in get_module
self.visit(top_node)
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/visitor.py", line 190, in visit
super().visit(node)
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/base.py", line 22, in visit
getattr(self, f"visit_{node.kind}", self.generic_visit)(node)  # type: ignore[attr-defined]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/visitor.py", line 221, in visit_module
self.generic_visit(node)
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/visitor.py", line 203, in generic_visit
self.visit(child)
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/visitor.py", line 190, in visit
super().visit(node)
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/base.py", line 22, in visit
getattr(self, f"visit_{node.kind}", self.generic_visit)(node)  # type: ignore[attr-defined]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/visitor.py", line 478, in visit_functiondef
self.handle_function(node)
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/visitor.py", line 342, in handle_function
labels |= self.decorators_to_labels(decorators)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.local/lib/venv/skimagedev/lib/python3.11/site-packages/griffe/agents/visitor.py", line 276, in decorators_to_labels
decorator_value = decorator.value.split("(", 1)[0]
^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
```

</details>

```console
$ mkdocs build -v
bash: mkdocs: command not found
```

**To Reproduce**

You can reproduce the offending bug by calling griffe on the following minimal example file:

```python
# file: minimal_example.py

class Transform:
    def estimate(self):
        return True


def decorate(func):
    def wrapped(*args, **kwargs):
        return func(*args **kwargs)
    return wrapped


@decorate((t := Transform()).estimate() and t)
def test(tform):
    pass
```

**Expected behavior**

griffe not raising an error.

**System (please complete the following information):**
- `griffe` version: 0.27.1
- Python version: 3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]
- OS: Linux-6.3.2-arch1-1-x86_64-with-glibc2.37

**Additional context**

**Comment by pawamoy** [comment]
It looks like it's already handled in latest version. Can you please try again with 0.28.2?

**Comment by lagru** [comment]
Yes, just tested this with griffe 0.29.0 and it seems fixed. Because of the previously reported error, I didn't notice that the snippet above also doesn't run with Python itself. Here's an updated snippet in case it ever comes up in the future again:

```python
# file: minimal_example.py

class Transform:
    def estimate(self):
        return True

def decorate(t):
    def wrapped(func):
        return func(t)
    return wrapped

@decorate((t := Transform()).estimate() and t)
def test(tform):
    print(tform)

```

**Comment by lagru** [comment]
Thanks for addressing it. :)
