### ISSUE TITLE
Could not resolve abc.abstractmethod

### ISSUE THREAD

**Issue by corykinney** [mkdocstrings/griffe#37]
**Describe the bug**
`griffe` appears to have an issue with `abc.abstractmethod`. 

**To Reproduce**
I'm attempting to generate documentation using the experimental python handler of `mkdocstrings` on code that includes abstract methods. The source includes a class definition similar to:

```py
from abc import abstractmethod
from typing_extensions import Protocol

class A(Protocol):
    @property
    @abstractmethod
    def prop(self):
        raise NotImplementedError

    @prop.setter
    @abstractmethod
    def prop(self, value):
        raise NotImplementedError

```

I believe this is a minimally reproducible example (if not the actual file is [here](https://github.com/VasuLab/PyRGFROSH/blob/main/rgfrosh.py)). It produces the following error message:

```
ERROR    -  Error reading page 'reference.md': Could not resolve abc.abstractmethod
Traceback (most recent call last):
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\griffe\dataclasses.py", line 859, in resolve_target
    resolved = self.modules_collection[self.target_path]
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\griffe\mixins.py", line 26, in __getitem__
    return self.members[parts[0]][parts[1]]  # type: ignore[attr-defined]
KeyError: 'abc'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\cory\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\cory\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Cory\AppData\Local\Programs\Python\Python38\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\mkdocs\__main__.py", line 177, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, **kwargs)
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\mkdocs\commands\serve.py", line 54, in serve
    config = builder()
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\mkdocs\commands\serve.py", line 49, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\mkdocs\commands\build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\mkdocs\commands\build.py", line 174, in _populate_page
    page.render(config, files)
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\mkdocs\structure\pages.py", line 174, in render
    self.content = md.convert(self.markdown)
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\markdown\core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\markdown\blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\markdown\blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\markdown\blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\mkdocstrings\extension.py", line 120, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\mkdocstrings\extension.py", line 199, in _process_block
    rendered = handler.renderer.render(data, rendering)
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\mkdocstrings_handlers\python\renderer.py", line 124, in render
    return template.render(
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\mkdocstrings_handlers\python\templates\material\module.html", line 1, in top-level template code
    {% extends "_base/module.html" %}
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\mkdocstrings_handlers\python\templates\material\_base\module.html", line 2, in top-level template code
    {% if config.show_if_no_docstring or module.has_docstrings %}
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\griffe\dataclasses.py", line 353, in has_docstrings
    return self.has_docstring or any(member.has_docstrings for member in self.members.values())  # noqa: DAR201
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\griffe\dataclasses.py", line 353, in <genexpr>
    return self.has_docstring or any(member.has_docstrings for member in self.members.values())  # noqa: DAR201
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\griffe\dataclasses.py", line 759, in __getattr__
    attr = getattr(self.target, name)
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\griffe\dataclasses.py", line 836, in target
    self.resolve_target()
  File "c:\users\cory\appdata\local\programs\python\python38\lib\site-packages\griffe\dataclasses.py", line 861, in resolve_target
    raise AliasResolutionError(self.target_path) from error
griffe.exceptions.AliasResolutionError: Could not resolve abc.abstractmethod

```

**System (please complete the following information):**
- `griffe` version: 0.11.3
- Python version: 3.8
- OS: Windows 10

**Comment by pawamoy** [comment]
Yaaaay feedback incoming :sunglasses: :open_umbrella: 
Thanks a lot for testing Griffe!

Let me investigate and I'll get back to you.
