### ISSUE TITLE
`typing.Tuple` not treated like a subscriptable object

### ISSUE THREAD

**Issue by 2bndy5** [mkdocstrings/griffe#95]
**Describe the bug**
I cannot document sequence-like return type inferred from the signature annotation. `Tuple[x, x]` throws a "index out of range" exception.

Please feel free to edit the this issue's title if it is misleading or incorrect.

**To Reproduce**
1. document a function
    ```py
    def parse_ignore_option(paths: str) -> Tuple[list, list]:  # should be -> Tuple[List[str], List[str]]:
        """Parse a given string of paths (separated by a '|') into `ignored` and
        `not_ignored` lists of strings.

        Args:
            paths: This argument conforms to the CLI arg `--ignore` (or `-i`).

        Returns:
            A tuple of lists in which each list is a set of strings.
            - index 0 is the `ignored` list
            - index 1 is the `not_ignored` list
        """
    ```
2. Run command `mkdocs build`
3. fails with traceback

<details><summary>Full traceback</summary>

```
ERROR    -  Error reading page 'API Reference\cpp_linter.run.md': list index out of range
Traceback (most recent call last):
  File "C:\Users\ytreh\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ytreh\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "path\to\venv\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "path\to\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "path\to\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "path\to\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "path\to\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "path\to\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "path\to\venv\lib\site-packages\mkdocs\__main__.py", line 192, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "path\to\venv\lib\site-packages\mkdocs\commands\build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "path\to\venv\lib\site-packages\mkdocs\commands\build.py", line 174, in _populate_page
    page.render(config, files)
  File "path\to\venv\lib\site-packages\mkdocs\structure\pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "path\to\venv\lib\site-packages\markdown\core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "path\to\venv\lib\site-packages\markdown\blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "path\to\venv\lib\site-packages\markdown\blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "path\to\venv\lib\site-packages\markdown\blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "path\to\venv\lib\site-packages\mkdocstrings\extension.py", line 121, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
  File "path\to\venv\lib\site-packages\mkdocstrings\extension.py", line 209, in _process_block
    rendered = handler.render(data, options)
  File "path\to\venv\lib\site-packages\mkdocstrings_handlers\python\handler.py", line 232, in render
    return template.render(
  File "path\to\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "path\to\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "path\to\venv\lib\site-packages\mkdocstrings_handlers\python\templates\material\module.html", line 1, in top-level template code
    {% extends "_base/module.html" %}
  File "path\to\venv\lib\site-packages\mkdocstrings_handlers\python\templates\material\_base\module.html", line 58, in top-level template code
    {% include "children.html" with context %}
  File "path\to\venv\lib\site-packages\mkdocstrings_handlers\python\templates\material\children.html", line 1, in top-level template code
    {% extends "_base/children.html" %}
  File "path\to\venv\lib\site-packages\mkdocstrings_handlers\python\templates\material\_base\children.html", line 61, in top-level template code
    {% include "function.html" with context %}
  File "path\to\venv\lib\site-packages\mkdocstrings_handlers\python\templates\material\function.html", line 1, in top-level template code
    {% extends "_base/function.html" %}
  File "path\to\venv\lib\site-packages\mkdocstrings_handlers\python\templates\material\_base\function.html", line 60, in top-level template code
    <div class="doc doc-contents {% if root %}first{% endif %}">
  File "path\to\venv\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
  File "C:\Users\ytreh\AppData\Local\Programs\Python\Python310\lib\functools.py", line 981, in __get__
    val = self.func(instance)
  File "path\to\venv\lib\site-packages\griffe\dataclasses.py", line 142, in parsed
    return self.parse()
  File "path\to\venv\lib\site-packages\griffe\dataclasses.py", line 155, in parse
    return parse(self, parser or self.parser, **(options or self.parser_options))
  File "path\to\venv\lib\site-packages\griffe\docstrings\parsers.py", line 51, in parse
    return parsers[parser](docstring, **options)  # type: ignore[operator]
  File "path\to\venv\lib\site-packages\griffe\docstrings\google.py", line 673, in parse
    section, offset = reader(docstring, offset + 1, **options)  # type: ignore[operator]
  File "path\to\venv\lib\site-packages\griffe\docstrings\google.py", line 369, in _read_returns_section
    annotation = annotation.tuple_item(index)
  File "path\to\venv\lib\site-packages\griffe\expressions.py", line 170, in tuple_item
    return self[2][2 * nth]
IndexError: list index out of range
```
</details>

**Expected behavior**
I expected the plugin to understand that `typing.Tuple` is subscriptable. Historically, I've used `tuple` as the return type without problems, but this doesn't satisfy stricter mypy configs.

**System (please complete the following information):**
- `griffe` version: 0.20.0
- Python version: 3.x (tried on 3.7-3.10)
- OS: Windows or Linux (tried both)

**Additional context**
This might be a duplicate of #69, but I'm not sure because this doesn't seem related to the content of the docstring.

**Comment by pawamoy** [comment]
Hello, thanks for the report. The issue is probably because of the way we parse the Returns section. Since we added support for documenting multiple return value, each line is considered a new item, hence Griffe will try to split the return type, and it will fail.
A quick solution would be to indent your continuation lines:

```
    Returns:
        A tuple of lists in which each list is a set of strings.
            - index 0 is the `ignored` list
            - index 1 is the `not_ignored` list
```

The long-term solution is to allow users to enable/disable multiple return values, so that they don't have to indent their single returned value description.

**Comment by 2bndy5** [comment]
Thanks, this error output could simply use more context. I was able to rememdy this using the proper annotations:
```py
def parse_ignore_option(paths: str) -> Tuple[List[str], List[str]]:
    """Parse a given string of paths (separated by a '|') into `ignored` and
    `not_ignored` lists of strings.

    Args:
        paths: This argument conforms to the CLI arg `--ignore` (or `-i`).

    Returns: Returns a tuple of lists in which each list is a set of strings.
        index 0 is the `ignored` list
        index 1 is the `not_ignored` list
    """
```
Although I'm not particularly happy about the type annotations gettings stripped from the signature:
![image](https://user-images.githubusercontent.com/14963867/185236880-8c51088f-9efe-4aa8-b248-df5cf82cd9c9.png)

**Comment by pawamoy** [comment]
> Although I'm not particularly happy about the type annotations gettings stripped from the signature:

This isn't related to this issue. You can enable annotations in signature with the `show_signature_annotations` option.

**Comment by AntoineD** [comment]
> Hello, thanks for the report. The issue is probably because of the way we parse the Returns section. Since we added support for documenting multiple return value, each line is considered a new item, hence Griffe will try to split the return type, and it will fail. A quick solution would be to indent your continuation lines:
> 
> ```
>     Returns:
>         A tuple of lists in which each list is a set of strings.
>             - index 0 is the `ignored` list
>             - index 1 is the `not_ignored` list
> ```
> 
> The long-term solution is to allow users to enable/disable multiple return values, so that they don't have to indent their single returned value description.

@pawamoy Is the long-term solution available or planned?

**Comment by pawamoy** [comment]
It's planned :)

**Comment by AntoineD** [comment]
With the currently supported format of the Returns section, how to document a return value that could be a tuple or another non tuple type?
For instance `def f() -> int | tuple[int, int]`.

**Comment by pawamoy** [comment]
No other choice than to document it using a single item.

**Comment by AntoineD** [comment]
> It's planned :)

May I help you?

**Comment by pawamoy** [comment]
Sure, you can help by making this configurable in Griffe, in the Google docstrings parser :) A new option like `returns_multiple_items`, defaulting to true to match and maintain the current behavior. Then once Griffe supports it we can document it in mkdocstrings-python.

**Comment by AntoineD** [comment]
> Sure, you can help by making this configurable in Griffe, in the Google docstrings parser :) A new option like `returns_multiple_items`, defaulting to true to match and maintain the current behavior. Then once Griffe supports it we can document it in mkdocstrings-python.

Thank you, I'll try to figure it out.
